services:
  db:
    image: docker.io/mariadb:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./config/logs/sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wp_net

  wp:
    image: docker.io/wordpress:6.8.1-php8.4-fpm-alpine
    container_name: wp
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME','https://localhost.test' );
        define( 'WP_SITEURL','https://localhost.test' );
        define( 'FS_METHOD', 'direct' );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        @ini_set( 'display_errors', 0 );
        define( 'POST_REVISIONS', false );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_CACHE', true );
        define( 'WP_MEMORY_LIMIT', '256M' );
        define( 'FORCE_SSL_ADMIN', true );
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
    networks:
      - wp_net

  wpcli:
    image: docker.io/wordpress:cli-2.12.0-php8.4
    container_name: wpcli
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_net

  nginx:
    image: docker.io/nginx:1.28-alpine3.21
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html:ro
      - ./config/logs/nginx:/var/log/nginx
      - ./config/site.conf:/etc/nginx/snippets/site.conf:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - wp
    networks:
      wp_net:
        aliases:
          - localhost.test

volumes:
  wp_data:

networks:
  wp_net:
    driver: bridge
